In [2]:
import numpy as np
from time import process_time

In [3]:
python_list=[i for i in range(100000)]
start_time= process_time()
python_list=[i+5 for i in python_list]
end_time = process_time()
print(end_time - start_time)

0.0


In [4]:
np_array=np.array([i for i in range(100000)])
start_time=process_time()
np_array +=5
end_time= process_time()
print(end_time - start_time)

0.015625


In [7]:
type(np_array)

numpy.ndarray

In [8]:
a=np_array([1,2,3,4])
print(a)
a.shape
a=np_array([1,2,3,4][1,2,3,4])


[1 2 3 4]


(4,)

In [13]:
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
x=np.ones((4,5))
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [17]:
y=np.full((5,4),5)
print(y)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [18]:
y=np.full((5,4),0)
print(y)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [19]:
e=np.eye(5)
print(e)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [20]:
b=np.random.random((3,4))
print(b)

[[0.53169686 0.55840012 0.4848844  0.90132511]
 [0.20401226 0.4064902  0.25844001 0.45201217]
 [0.42836992 0.76578963 0.24596483 0.27772609]]
