In [3]:
import numpy as np
from time import process_time

In [2]:
python_list=[i for i in range(100000)]
start_time= process_time()
python_list=[i+5 for i in python_list]
end_time = process_time()
print(end_time - start_time)

0.015625


In [3]:
np_array=np.array([i for i in range(100000)])
start_time=process_time()
np_array +=5
end_time= process_time()
print(end_time - start_time)

0.0


In [4]:
type(np_array)

numpy.ndarray

In [6]:
a=np.array([1,2,3,4])
print(a)
a.shape


[1 2 3 4]


(4,)

In [5]:
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
x=np.ones((4,5))
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [8]:
y=np.full((5,4),5)
print(y)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [9]:
y=np.full((5,4),0)
print(y)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [10]:
e=np.eye(5)
print(e)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [11]:
b=np.random.random((3,4))
print(b)

[[0.94200725 0.3592037  0.23462415 0.06793067]
 [0.57728894 0.28532472 0.94729534 0.06063843]
 [0.88853038 0.41616634 0.06365442 0.37321382]]


In [12]:
a=[1,2,3,4]
variable=np.asarray(a)
print(variable)


[1 2 3 4]


In [13]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(0,30,(3,3))
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(np.add(a,b))


[[2 8 8]
 [1 4 1]
 [1 6 7]]
[[10 13 23]
 [ 5 11  2]
 [ 4 21  6]]
[[12 21 31]
 [ 6 15  3]
 [ 5 27 13]]
[[ -8  -5 -15]
 [ -4  -7  -1]
 [ -3 -15   1]]
[[ 20 104 184]
 [  5  44   2]
 [  4 126  42]]
[[12 21 31]
 [ 6 15  3]
 [ 5 27 13]]


In [14]:
#transpose
k=np.random.randint(0,10,(3,3))
print(k)
print(k.shape)


[[0 5 4]
 [6 2 9]
 [6 1 0]]
(3, 3)
